[[boost]]
arch = "i686"
git-tree-sha1 = "9f35d578e8d7131b548e37aff5eac910579ce1b8"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "389c8eba30c768b8f0d635d343a605456cf86c9c691745c2f5b294e3b8c3dc60"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.i686-linux-gnu.tar.gz"
[[boost]]
arch = "i686"
git-tree-sha1 = "01bcb8d1d5963e391eef399aae431e5338f1b808"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "121bcc58abacc8efa622de210e9ad8e05bba9d9ea47ddf2657ec4b75fcdc8ab7"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.i686-linux-musl.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "2c91a6bab0eb60dc6195c6c499a47fc7da23819e"
os = "macos"

    [[boost.download]]
    sha256 = "805e3bb3531824b09a6f82b3554c2b380882f6691253c2db4cdfde8112e08aa4"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.x86_64-apple-darwin14.tar.gz"
[[boost]]
arch = "powerpc64le"
git-tree-sha1 = "125d9ca93afa16b13f0e7bcae58029ed7ad6d9af"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "3777705d9e2e66a829e961ff081e2a6664aad7cd567dd4b844bf88b872623dcb"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.powerpc64le-linux-gnu.tar.gz"
[[boost]]
arch = "aarch64"
git-tree-sha1 = "a552fdfde69152c5e2f746ff0387631a133452ec"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "6ee57b03c03112f21e88fc9ab21bd7b003b4d66cf6037201d7ea314ca59c0b05"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.aarch64-linux-gnu.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "40ce2034055270c0742519a27e1a530aa3737f0e"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "169f386eed4bdbfa099a4aa9db06582aeef44c887ee2ba629b51f334dccbebf2"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.x86_64-linux-musl.tar.gz"
[[boost]]
arch = "aarch64"
git-tree-sha1 = "ef46c0ff87376fc4d8d77437111ef97e0fdaa765"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "1428b9edd9525097427f308db09b58f8edee92b647d2d993e7d4d7a6e1e4b9ff"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.aarch64-linux-musl.tar.gz"
[[boost]]
arch = "armv7l"
git-tree-sha1 = "58c1e16d9f11794df49c561559e35f2e032c2f31"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "d50ba416fce2936c5e94b281f94c51c9a23330da10709be21061496ca7a2c03a"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.arm-linux-musleabihf.tar.gz"
[[boost]]
arch = "i686"
git-tree-sha1 = "0c7c405f7011af0314cbef0dbafb14f8ceb52fde"
os = "windows"

    [[boost.download]]
    sha256 = "8b4f157d14c09d02f44e2d6ba49eaa5a1a261fa04f47a5e2fcf3544da4b95fee"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.i686-w64-mingw32.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "68d89a41b0558fadb5a7e330ceecaf86be9beb14"
os = "freebsd"

    [[boost.download]]
    sha256 = "f50c8dd070c6893737dcd07422184a189c41203e40c69c2678d4b065686edf55"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.x86_64-unknown-freebsd11.1.tar.gz"
[[boost]]
arch = "armv7l"
git-tree-sha1 = "208e9e4998780925cb20ed21e9b9e7208d5cd097"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "5ed525788fe9da79d63d56122d6120ca63e66201a479c2f95922662bbddb69f3"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.arm-linux-gnueabihf.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "7b86a7ef6c4692f8157c49dd696c33fb1344c5b7"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "43b1b533cffd7a3cf9f1440cda00931cface8ebe980f0b3ded796883a096ebdb"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.x86_64-linux-gnu.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "bffaec680708623b2ec0bc6093b58a9a7e475b0f"
os = "windows"

    [[boost.download]]
    sha256 = "79b064f490c4049866dbc6f02fceccc2c2809854157495b0bce426e08f54cd8b"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+1/boost.v1.71.0.x86_64-w64-mingw32.tar.gz"
