[[boost]]
arch = "aarch64"
git-tree-sha1 = "49c8d621c8f6977f51006c549e6b0f6bcce53eae"
os = "macos"

    [[boost.download]]
    sha256 = "8d3cd1cc5351a1526ad27c22e90e7647efc63d679d94a2a139e59294b2bbcdac"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.aarch64-apple-darwin.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4efcd52ae46328e8e882959b19a6a93902fe4ad0"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "f22f6df47c598c08bb6abb14252b884092e9bd7bf75b6a03ec3a4b8bceb09985"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.aarch64-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1a94a39a6dfd738d0bb558e6ff87d9eaae0a60e"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "1912c69d8ab36eba4fcf2e30d1535a5b2266efb438227c1998d68e0cb6a66fa0"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.aarch64-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5ca7872b9d5e7d4db9f9a0d46b2771cca796d8e"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "16690be752c951cb3014a19b8208ea0efb9fdf950aa620eb33c5ae6787cf192a"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.aarch64-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e2703fcff6ab26632294c0efa7c1e507f0acf8f"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "de323ad0a39e8f554b49e5f8db82ac6c3f9190dcd2f94d876fa1077c760a5b4e"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.aarch64-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "aarch64"
git-tree-sha1 = "70afb9239e5538ba4057af55ed7349cb8d6b1ec3"
os = "freebsd"

    [[boost.download]]
    sha256 = "d46f25e25d0ef689f7a0333ec1c0851d06a368293b1e0a17e92520bdf6271ebb"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.aarch64-unknown-freebsd.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0daba55570247f1b3e208ad5c754f74f3af6f35"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "31e4be7006e6772841facdf38f1d958627d8621084ed8f0ad729f72da8ba4483"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ae48918d849a70b299d8cb562ef607f5c695bb4"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "7bbde9a138401dbf60fbf3be33ccbd7334281b140571bfb68e8151b0c23a2e8e"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3252598323f0e10d93c9fc112f01b3c440f865bb"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "35dafeebeae469ee2587c97e5bb593f5d9324fcbcbdad1484743fec0d5bb2293"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7645cffeb7cf55028933200da91a4cb38116d1e"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "4c14534ca5c17411b537ffea4de78431b1a1a6c13f3f3ab7214524732daa49b7"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3024675e1c3aa5f15aaadc34262d59bf25a1cc98"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "dbde3e8a6b1b5057814fb78ba55c6ba185a8ab81900285ab5537c69e81871e32"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dffcb4188ffe5f7da5d0af07ba7cee69c46b7be"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "b620011d748720d5e692f8fd1eb324b254dc10f3cca64be50b1e2a36d2cdf294"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3823bd85bb6d397563392b27f220f4fbdb87c48f"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "ddbd360363e7cdd717ea094954c9da632276996091776ab14f9be74aa5e349c8"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b71cd8b26ddb28345b12ef75c572b0c03370230"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "61a59b129f9b3f93284ed5e171f812539232da3efe3e97b8d16210543aa38eec"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67add76bfb228fecc9888b5ade7142e53f282106"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "db76098fdd60eeb04c66d43aa6639f6df9916018bb3bfa4381ba485997e76779"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.i686-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df484532139ec0d40120f73e364bca006a86a73a"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "12f7d088fdc55c2be96a960ad9818fe38ef240c5586093159d3462f5f4731807"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.i686-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d483c39d647c7599e7b78352d9280b1d78eb7672"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "bc1e2d17a1a145324d55f240d6f76f483b62938110e98de75e9bb9d75dea9cbe"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.i686-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f90b29f1258562d14ffe5a07569fd5233716599"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "b9b9b7ab30e8fcf8e9af0c6177363bc68c2d0cf8f366c3e19fa3209bb4dd3917"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.i686-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29b032c7527f19182f693eda1ff89f779713de2f"
os = "windows"

    [[boost.download]]
    sha256 = "e3a64417f40077e6fb79f83b398c84ccf9eec560c40be627cb023b65487a2786"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.i686-w64-mingw32-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d82044d732c2f20a1c628c635b345b9425c1f700"
os = "windows"

    [[boost.download]]
    sha256 = "b14dda3e8f5bf3d2b11ac33d75f2cf3af87a149726776a00312db278fea8832a"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.i686-w64-mingw32-cxx11.tar.gz"
[[boost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d55c2c632c0a150efe10a7c4746a9ec126fe0b4"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "bc7426b8df626541a3d05bf00a46f594e4f38ce3b2c521c797ac6e8114ae01a6"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "472e9ef03b0afb07cb7f923308974dad78215933"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "aa217136060c1c4214cf12c49019d9a63e3dbf3554ee58fec4f2c5d99136dfbe"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8d18a76ee10d3c57aecc043ef71c76bb1e5ae565"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "9f5bd39111d9625e606d489062c30c2b54b5c65073ec922416249f11cfd8c9c6"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.riscv64-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e83548fb44da0e75aceb9b2b31b354c9d010fd8"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "da4a1bbf9cf4aca50280cdcc40a519f7278cd92aff443b3b28b0c197bd5cb2a0"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.riscv64-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "341dab8a4d7e0798a6a68b1bcc4793808bc73298"
os = "macos"

    [[boost.download]]
    sha256 = "1cf9506a4cbebd14534de5ccc65c441c1f3f4c5ea384484c15ddf1a720eae01d"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-apple-darwin.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3e9057544fcd9cc5b117608713b5be7712a9c05"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "e1094376b218fec86d6373b177c7d4779173814875b19d4685a6c955f584697f"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d5bf8a817e520b6422a0630700ccac87eb57e9e"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "4d503214f46216c6f8cba40dd7148bd0b411e0286d216a93641fa02afcdf5dc6"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6656c672747f2e1bd0553e3a0ce76d33e683af3"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "b1d6c6392d25512761edd8a69b7f90d5c5aaa5d7a75d31619f043f5d2c0ec0ac"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74c6b20191874e2dde6bc41fcffdc53272e162d1"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "cdb07af5d1a59238f4fe538fa31cb9c0bfc244715876c0db852c6fa21f3c5955"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "ce760769fb2eb5708dd195295d89374c9610dfda"
os = "freebsd"

    [[boost.download]]
    sha256 = "ba1029de0c692706ef2dba4c7e91a87a4f5c2e982d55223c1aef723a92e35b93"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-unknown-freebsd.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a715f92bc1222c61118743ae2916229fdc791ffa"
os = "windows"

    [[boost.download]]
    sha256 = "1e45abadbd40eba90bcfa1006cd60167edf1dcebe4b71254b755de62fe7b4243"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f03b7ca1ba6685f7f593a765a21cb553bddb7e5d"
os = "windows"

    [[boost.download]]
    sha256 = "3e3fb06fc583f9d6ae8a8a9cee5c488d98588de827132eed320c291abe2bbdcd"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.87.0+0/boost.v1.87.0.x86_64-w64-mingw32-cxx11.tar.gz"
