[[boost]]
arch = "aarch64"
git-tree-sha1 = "0eb0e4fe1782c3b7e0a3f7bc2bcc5639792d2c79"
os = "macos"

    [[boost.download]]
    sha256 = "102dd160d8eac61c051b69627798af72c9a476befb9f0cb97e1f57685ae4b4a6"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.aarch64-apple-darwin.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "067e88e0e31f9572a49986a1f055d06c473d8bb3"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "b81c1f1831375d13cc3cfb4d92d4f3d6acfbd8e1d5a8eb9b706577fa686297eb"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.aarch64-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4cdf6b045a6a1fe5a23003be28ca57ae47e9851"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "d8075131ca489285bf51ff3be49c0a590d324e71e0133f8994615554e36a48ff"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.aarch64-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee68a70e2e17a001656b76305ec0d96da4984571"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "d156eaa48cbdf59028f0c838dd1dcda3598f9abe5dab5f03e1c77a30cc0c5573"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.aarch64-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51a53213560178b2161b99acf9acd6b4d3fefcc7"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "d65653e7fc10e0f36622394453cbd847d0bd1571d1fc59650125139358c5ceb2"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.aarch64-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aed5aab54ed8a6330fcb0b48d87130d2de980ffd"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "bf6e88afc9baaf6dac1b6677b2b0ea0f435c486e7bcef9a2d56ce98d1d8a288a"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f159df904419d7d3b4989bd0d867cb5d855024a1"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "dd1ad24840c2f0eb4c55cca01e24a656aca54814e4d0de5030a422084668646b"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6764b350fb8bd58c707e23766b652bb5cb4da131"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "9ddfcc8dbb94b3689055005a23cffa9b0389bb2c53cea4b5b1a56fd8c2ce93bc"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[boost]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9f57a54a1a9aeb87e4617a46bc14669c575922d"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "25f3b18ee5717d57fb3a398cbc96013118e07c2c0b75859eae0e3e9e05f925aa"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6f689df0f7a1f3673c229d176b3ea75c79d3cc5"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "170de2737863083642d3b8fb59b203e3da95411f8904eebede117c06dbba78ab"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d04d9a1e824623c9b3a523800b26db0bb2655f06"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "157a93dc2fe459ce46ec13af9d6b73b41821837594d03868deb94bcdcb4e7cf0"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39a946a00edc8af2ac31843e54c5823c65efc633"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "d0fe2f404c1c1701313a31290973006688b89d4abf133a7f1da5f1f56120d455"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7c73897a3e2bb5c28f2223fd6de119af8f07539"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "e080b573ac7d77a29f5270712f864bb2aa81c528c24b135151eee41919b82169"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8532223fe4ef295ec8fb849607841bd617e1d70c"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "ee0226233f06b7667707c0434f7e084d5a392288e7eab04888fbba59c4d05b07"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.i686-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2e8948cfe496ce03ae80131dbaaa93168846c52"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "7754eee8a38b67e5d1a323266692e193164b9ee033bfffa66784b340eb76a1ef"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.i686-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "534c2cc2e708e624b792f3e4eada644611e37812"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "5a495e509f8eff6b2a83740619b3d98285eda11915de8053dc101b5f3697862f"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.i686-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a579ea6d6835ecdf71519de52030a07ee346a33"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "f7872f1884cf473a8e5b7a974ade7d3bf52778f6b44c5b76052b8f7b7231e61d"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.i686-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d06c2dd2f43a83e4e08e733c2752f097e9af309b"
os = "windows"

    [[boost.download]]
    sha256 = "a14da7a370ae7e75dd752ea2a25d849b68fe0801d6d76577ab9a7fd0789cb14c"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.i686-w64-mingw32-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94128d27c6772f17c5b67ee26d6eb55f3be3a9c0"
os = "windows"

    [[boost.download]]
    sha256 = "191dfb5bab354dcc060f74338f05ed0164180e26129083ba11f9fcbb53e06dfd"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.i686-w64-mingw32-cxx11.tar.gz"
[[boost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbbd47f0785a56bc2d4b7d9b312ecf5358c0a19c"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "f78d90808a5e0aa6b901c03abf4cb5be83327a491de3cfdf1df6fa64fd8c341b"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40ab71fa7578502ef6399afee10eb380694f5fcb"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "2a7dfa38d5aa39607f9627302d724787fb164283f6da6c42900ae9db39f8ecbd"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "9fd8cbeaa10466b38726fc4d2a31399bb1cdcd81"
os = "macos"

    [[boost.download]]
    sha256 = "6e0810af0fbf9a84ef075bba07d51623f18dd9eeabef61a8c74ba6bf9a459ce9"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-apple-darwin.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f643e411ac88490969a9d3d6130029f67a570e9"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "bf8530914f0eff7a899a48603d813a9c92330fa68f3b200ba8fdb97d07ecec18"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e486cf987b892f0435f3d745c329d3e7a038ab5"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "5ca2df2199fb57ce1c6c60acb2f155a056acc6fdc5193b00a534549d74d1cbb1"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43e0b1476ef6fd2c04386eaae79e9ee5d38e18e8"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "e7e2d78dc80d177077dc3df4ce15c004f2171248a15892a04964e2f8986f04be"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "216122a8e41fe9b1a3641c6ee8877a9ac3c63339"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "869954edfbcdb2d233271af3f216018beeaaef93aae307ef15f2867c3a02840c"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "29466b7b7c55e47ec754e0d1e4d2ba920a1a570d"
os = "freebsd"

    [[boost.download]]
    sha256 = "2754f8a48d031122f88639144e84a78c33fd2e8edce89088edd896c0d6b54a10"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-unknown-freebsd.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88340739dfba69e0368a3abf31cc387a3e6a7ee5"
os = "windows"

    [[boost.download]]
    sha256 = "693d958d69dba3f1fe86e16b11863bd0eaab0e3fa940c759b0b396edc7011a61"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52e2c05127fc3d971b7ea72f9052d37d8cc89e3a"
os = "windows"

    [[boost.download]]
    sha256 = "eeffb2cfd52d51c7e1f9465bb9cdb8aaab4b0190f11863e4c1f92300d1b9b652"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.76.0+0/boost.v1.76.0.x86_64-w64-mingw32-cxx11.tar.gz"
