[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4036c3643951aeeaa3614241380ea39b04f71d72"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "0b215fb8f83f3ef91db05f0ad5f6b43ded6d2026ce46ad893e3b9622d9542b64"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.aarch64-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b8758bf3ae8127b6cfee50b19a9a055c343f6a1"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "77c6d295a03c9ba8f85beaec5d1ffd51f856440729f39275738a811a0e99f4be"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.aarch64-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68713a066dfa14940dac37e702db3fe9587ef8c3"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "99444a00b6e2efe0c7cf1a07f03cf71f8e52250aa6ee54960c619923efc60581"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.aarch64-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ad997bdba703654ef419e4358b440bdf2116a0a"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "7450ec8e09a095f3006a143731835328975d3a12800a35a70c9aa9584ab495b6"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.aarch64-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be26f4630cec9aa35829cc0185dad1f6df16374"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "662e270728e4814390fc9019092a4d1f1eda5a5f6ef7c7e380ef2150b3697d66"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f1847f9ca2b4b300f9f781867b18ee4164c668f"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "d1682ea18a244e4acd31695bd0c14aa43a3e0a4d6686278276a9970c18f44799"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f59e831bd5fb61c9f40afaa57b64993ba80ca0e1"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "c89bf2a84c656ba1b16e2eddebe3fa6991ea2752333d9f84c4f36029f737fca1"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[boost]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c8033e36915b2106ce46d2205dcb5287e9f668f"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "1c5091e3e44a1e03a3cce5edf7372dc1c71c2e06b370310f0ec9b77bcb53b021"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17987869def21754a6f8a0f793130d51d75f5c54"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "f5111f7903a229baaa53b3303d0a6467f82fde978721b857034f0314eef02ae7"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.i686-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7abc5143d67bea3dd417272109b64dc1c27f767"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "d0813449d4f4ef47d4d270cfc3671112fe85b40092a73ddfa2d681dfd09b6da8"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.i686-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a492dae7ccb0e4854ed8bb81b692afa8e096b56"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "df82d691508f5322e06f838a9aa68059dd4057ba7474efe4ad9efcb07ec5d7d0"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.i686-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab05636286b81fd27b135cb790c75cebd2f8c505"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "b726173dabfaeb6281b734eab48eaccb2fa937702fbbbcf6393b18f5a12a497e"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.i686-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08ccb73f7f781a241fcf989c1ab7e3c511b93f17"
os = "windows"

    [[boost.download]]
    sha256 = "a2a94b2a0d49aed86fdc54a8205e1ea8d4d81254b3249fc9db46dba6736b34c6"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.i686-w64-mingw32-cxx03.tar.gz"
[[boost]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "841e6f2ee9ea6babc97cc61624a1c7c222095243"
os = "windows"

    [[boost.download]]
    sha256 = "5d4cfe0ffc5334d19a841bc5318f35d12fce1202755cd99bbfd8feecebbeffd0"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.i686-w64-mingw32-cxx11.tar.gz"
[[boost]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1570646593365b8ade1b29e8a8f7db2979f755a9"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "17621c272d37ea53d103be817fdd1cc82f2d8f6d752d3dea6fa0e7c5d0e2efb9"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67c6dea87a26e2b7dc076dda4988d34ef954205b"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "acf198b876d0f9bfff8ca389e1a01b162135dbb6ff485e857df0d8fe71e9f994"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "cb6483a6eae3173e005725c6c064755c72a8b2cb"
os = "macos"

    [[boost.download]]
    sha256 = "d384717df4a3d9877018cf5ec1f27fa6c4a0c0da4c652e8a88627379cd4c736a"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-apple-darwin.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39279c46dab8b5eb6eff5cedaf6cb6b463a9fc01"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "136485f46ea055735608973d925a1e7fa1656492082f6e53306ead98142f5c60"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-linux-gnu-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9960e060b732618174ffd95804d6635833f99513"
libc = "glibc"
os = "linux"

    [[boost.download]]
    sha256 = "eb2ebd6e03bc027b42d7b675a55e76aa60f818ae4344bfc82bd751e287c2026a"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-linux-gnu-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec7d633af1194ce6b4a5295a113543a35ddd88b9"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "b337ed93861375c10978fccfb3c2b975c937609d29ec7c134081b664c8754b20"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-linux-musl-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16dc7a70ae58fac4dae525f34220fb2269a121a2"
libc = "musl"
os = "linux"

    [[boost.download]]
    sha256 = "070fd43b6250df93d54df232a3a3ceff7b3566bcc1d0ee9285f7a7580882a943"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-linux-musl-cxx11.tar.gz"
[[boost]]
arch = "x86_64"
git-tree-sha1 = "6e3ba066e0ab0501b2dbb00ebc20ba75ba50f0bb"
os = "freebsd"

    [[boost.download]]
    sha256 = "7fb6d72b5ad95a2b0baf3b224f9f21fe6913e056f14737a2748497f4726a7eff"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-unknown-freebsd.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "799c0b973b2174b45952de5f84713f67f47ad91f"
os = "windows"

    [[boost.download]]
    sha256 = "51b6750393fdb013515843457e1483a264f3f42e2238a12f8c3469fb032cd3b6"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[boost]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fc6b9a36a02b8b6433d12d930a2eb91b1dc1303"
os = "windows"

    [[boost.download]]
    sha256 = "8f4636833ab0d4e9b2128634412560ffc9d9a67db3b3c1c2b8a79f7db036ccd4"
    url = "https://github.com/JuliaBinaryWrappers/boost_jll.jl/releases/download/boost-v1.71.0+3/boost.v1.71.0.x86_64-w64-mingw32-cxx11.tar.gz"
