# Autogenerated wrapper script for boost_jll for aarch64-apple-darwin
export libboost_atomic, libboost_chrono, libboost_container, libboost_context, libboost_contract, libboost_coroutine, libboost_date_time, libboost_filesystem, libboost_graph, libboost_iostreams, libboost_log, libboost_log_setup, libboost_prg_exec_monitor, libboost_program_options, libboost_random, libboost_regex, libboost_serialization, libboost_stacktrace_basic, libboost_stacktrace_noop, libboost_system, libboost_thread, libboost_timer, libboost_type_erasure, libboost_unit_test_framework, libboost_wave, libboost_wserialization

using Zlib_jll
using Bzip2_jll
JLLWrappers.@generate_wrapper_header("boost")
JLLWrappers.@declare_library_product(libboost_atomic, "@rpath/libboost_atomic.dylib")
JLLWrappers.@declare_library_product(libboost_chrono, "@rpath/libboost_chrono.dylib")
JLLWrappers.@declare_library_product(libboost_container, "@rpath/libboost_container.dylib")
JLLWrappers.@declare_library_product(libboost_context, "@rpath/libboost_context.dylib")
JLLWrappers.@declare_library_product(libboost_contract, "@rpath/libboost_contract.dylib")
JLLWrappers.@declare_library_product(libboost_coroutine, "@rpath/libboost_coroutine.dylib")
JLLWrappers.@declare_library_product(libboost_date_time, "@rpath/libboost_date_time.dylib")
JLLWrappers.@declare_library_product(libboost_filesystem, "@rpath/libboost_filesystem.dylib")
JLLWrappers.@declare_library_product(libboost_graph, "@rpath/libboost_graph.dylib")
JLLWrappers.@declare_library_product(libboost_iostreams, "@rpath/libboost_iostreams.dylib")
JLLWrappers.@declare_library_product(libboost_log, "@rpath/libboost_log.dylib")
JLLWrappers.@declare_library_product(libboost_log_setup, "@rpath/libboost_log_setup.dylib")
JLLWrappers.@declare_library_product(libboost_prg_exec_monitor, "@rpath/libboost_prg_exec_monitor.dylib")
JLLWrappers.@declare_library_product(libboost_program_options, "@rpath/libboost_program_options.dylib")
JLLWrappers.@declare_library_product(libboost_random, "@rpath/libboost_random.dylib")
JLLWrappers.@declare_library_product(libboost_regex, "@rpath/libboost_regex.dylib")
JLLWrappers.@declare_library_product(libboost_serialization, "@rpath/libboost_serialization.dylib")
JLLWrappers.@declare_library_product(libboost_stacktrace_basic, "@rpath/libboost_stacktrace_basic.dylib")
JLLWrappers.@declare_library_product(libboost_stacktrace_noop, "@rpath/libboost_stacktrace_noop.dylib")
JLLWrappers.@declare_library_product(libboost_system, "@rpath/libboost_system.dylib")
JLLWrappers.@declare_library_product(libboost_thread, "@rpath/libboost_thread.dylib")
JLLWrappers.@declare_library_product(libboost_timer, "@rpath/libboost_timer.dylib")
JLLWrappers.@declare_library_product(libboost_type_erasure, "@rpath/libboost_type_erasure.dylib")
JLLWrappers.@declare_library_product(libboost_unit_test_framework, "@rpath/libboost_unit_test_framework.dylib")
JLLWrappers.@declare_library_product(libboost_wave, "@rpath/libboost_wave.dylib")
JLLWrappers.@declare_library_product(libboost_wserialization, "@rpath/libboost_wserialization.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Bzip2_jll)
    JLLWrappers.@init_library_product(
        libboost_atomic,
        "lib/libboost_atomic.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_chrono,
        "lib/libboost_chrono.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_container,
        "lib/libboost_container.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_context,
        "lib/libboost_context.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_contract,
        "lib/libboost_contract.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_coroutine,
        "lib/libboost_coroutine.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_date_time,
        "lib/libboost_date_time.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_filesystem,
        "lib/libboost_filesystem.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_graph,
        "lib/libboost_graph.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_iostreams,
        "lib/libboost_iostreams.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_log,
        "lib/libboost_log.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_log_setup,
        "lib/libboost_log_setup.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_prg_exec_monitor,
        "lib/libboost_prg_exec_monitor.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_program_options,
        "lib/libboost_program_options.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_random,
        "lib/libboost_random.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_regex,
        "lib/libboost_regex.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_serialization,
        "lib/libboost_serialization.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_stacktrace_basic,
        "lib/libboost_stacktrace_basic.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_stacktrace_noop,
        "lib/libboost_stacktrace_noop.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_system,
        "lib/libboost_system.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_thread,
        "lib/libboost_thread.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_timer,
        "lib/libboost_timer.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_type_erasure,
        "lib/libboost_type_erasure.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_unit_test_framework,
        "lib/libboost_unit_test_framework.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_wave,
        "lib/libboost_wave.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_wserialization,
        "lib/libboost_wserialization.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
