# Autogenerated wrapper script for boost_jll for x86_64-w64-mingw32-cxx03
export libboost_atomic, libboost_chrono, libboost_container, libboost_context, libboost_contract, libboost_coroutine, libboost_date_time, libboost_filesystem, libboost_graph, libboost_iostreams, libboost_log, libboost_log_setup, libboost_prg_exec_monitor, libboost_program_options, libboost_random, libboost_regex, libboost_serialization, libboost_stacktrace_basic, libboost_stacktrace_noop, libboost_system, libboost_thread, libboost_timer, libboost_type_erasure, libboost_unit_test_framework, libboost_wave, libboost_wserialization

JLLWrappers.@generate_wrapper_header("boost")
JLLWrappers.@declare_library_product(libboost_atomic, "libboost_atomic.dll")
JLLWrappers.@declare_library_product(libboost_chrono, "libboost_chrono.dll")
JLLWrappers.@declare_library_product(libboost_container, "libboost_container.dll")
JLLWrappers.@declare_library_product(libboost_context, "libboost_context.dll")
JLLWrappers.@declare_library_product(libboost_contract, "libboost_contract.dll")
JLLWrappers.@declare_library_product(libboost_coroutine, "libboost_coroutine.dll")
JLLWrappers.@declare_library_product(libboost_date_time, "libboost_date_time.dll")
JLLWrappers.@declare_library_product(libboost_filesystem, "libboost_filesystem.dll")
JLLWrappers.@declare_library_product(libboost_graph, "libboost_graph.dll")
JLLWrappers.@declare_library_product(libboost_iostreams, "libboost_iostreams.dll")
JLLWrappers.@declare_library_product(libboost_log, "libboost_log.dll")
JLLWrappers.@declare_library_product(libboost_log_setup, "libboost_log_setup.dll")
JLLWrappers.@declare_library_product(libboost_prg_exec_monitor, "libboost_prg_exec_monitor.dll")
JLLWrappers.@declare_library_product(libboost_program_options, "libboost_program_options.dll")
JLLWrappers.@declare_library_product(libboost_random, "libboost_random.dll")
JLLWrappers.@declare_library_product(libboost_regex, "libboost_regex.dll")
JLLWrappers.@declare_library_product(libboost_serialization, "libboost_serialization.dll")
JLLWrappers.@declare_library_product(libboost_stacktrace_basic, "libboost_stacktrace_basic.dll")
JLLWrappers.@declare_library_product(libboost_stacktrace_noop, "libboost_stacktrace_noop.dll")
JLLWrappers.@declare_library_product(libboost_system, "libboost_system.dll")
JLLWrappers.@declare_library_product(libboost_thread, "libboost_thread.dll")
JLLWrappers.@declare_library_product(libboost_timer, "libboost_timer.dll")
JLLWrappers.@declare_library_product(libboost_type_erasure, "libboost_type_erasure.dll")
JLLWrappers.@declare_library_product(libboost_unit_test_framework, "libboost_unit_test_framework.dll")
JLLWrappers.@declare_library_product(libboost_wave, "libboost_wave.dll")
JLLWrappers.@declare_library_product(libboost_wserialization, "libboost_wserialization.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libboost_atomic,
        "bin\\libboost_atomic.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_chrono,
        "bin\\libboost_chrono.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_container,
        "bin\\libboost_container.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_context,
        "bin\\libboost_context.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_contract,
        "bin\\libboost_contract.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_coroutine,
        "bin\\libboost_coroutine.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_date_time,
        "bin\\libboost_date_time.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_filesystem,
        "bin\\libboost_filesystem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_graph,
        "bin\\libboost_graph.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_iostreams,
        "bin\\libboost_iostreams.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_log,
        "bin\\libboost_log.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_log_setup,
        "bin\\libboost_log_setup.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_prg_exec_monitor,
        "bin\\libboost_prg_exec_monitor.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_program_options,
        "bin\\libboost_program_options.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_random,
        "bin\\libboost_random.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_regex,
        "bin\\libboost_regex.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_serialization,
        "bin\\libboost_serialization.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_stacktrace_basic,
        "bin\\libboost_stacktrace_basic.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_stacktrace_noop,
        "bin\\libboost_stacktrace_noop.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_system,
        "bin\\libboost_system.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_thread,
        "bin\\libboost_thread.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_timer,
        "bin\\libboost_timer.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_type_erasure,
        "bin\\libboost_type_erasure.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_unit_test_framework,
        "bin\\libboost_unit_test_framework.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_wave,
        "bin\\libboost_wave.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libboost_wserialization,
        "bin\\libboost_wserialization.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
